# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  uiSource : 'src'
  uiBuild  : 'build'
  variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js'
  
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm

- script: |  
    npm ci
    npm install
    npm run build
  displayName: 'npm update and build'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(uiBuild)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'